using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RPSX.Roles.CCO.Console;

[GenerateTypedNameReferences]
public sealed partial class CcoConsoleSquadControl : Control
{
    public CcoConsoleSquadControl(CCOConsoleBoundInterface bui, string prototypeID, string name, string description, bool canCall)
    {
        RobustXamlLoader.Load(this);

        Name.Text = name;
        Description.SetMessage(description);

        StartRitualButton.OnPressed += _ => bui.SendSpecialSquad(prototypeID);
        StartRitualButton.Disabled = canCall;
    }
}
