using Content.Shared.RPSX.Bank.PDA;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using PdaBankTransactions = Content.Client.RPSX.Bank.PDA.UI.Transactions.PdaBankTransactions;

namespace Content.Client.RPSX.Bank.PDA.UI;

[GenerateTypedNameReferences]
public sealed partial class PdaBankUiFragment : BoxContainer
{
    public PdaBankUiFragment()
    {
        RobustXamlLoader.Load(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
        Margin = new Thickness(8);
    }

    public void UpdateState(BankCartridgeUiState state)
    {
        Username.Text = state.Username;
        UserBalance.Text = $"{state.UserBalance}";

        TransactionsList.DisposeAllChildren();
        TransactionsList.RemoveAllChildren();

        foreach (var transaction in state.Transactions)
        {
            var transactionLayout = new PdaBankTransactions();
            transactionLayout.SetTransaction(transaction);
            TransactionsList.AddChild(transactionLayout);
        }
    }
}
