using Content.Shared.RPSX.Bank.Transactions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.RPSX.Bank.PDA.UI.Transactions;

[GenerateTypedNameReferences]
public sealed partial class PdaBankTransactions : PanelContainer
{
    public PdaBankTransactions()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetTransaction(BankTransaction transaction)
    {
        var transactionTypeMessage = GetMessage($"pda-bank-transaction-type-{transaction.Type}");
        TransactionType.SetMessage(transactionTypeMessage);

        var statusColor = GetStatusColor(transaction);
        var transactionStatus = GetMessage($"pda-bank-transaction-status-{transaction.Status}");
        TransactionStatus.SetMessage(transactionStatus, defaultColor: statusColor);

        var sumColor = GetSumColor(transaction);
        Sum.SetMessage(GetTransactionSum(transaction), defaultColor: sumColor);

        if (!Loc.TryGetString($"pda-bank-transaction-location-{transaction.Location}", out var location))
            location = transaction.Location;

        var formattedLocation = FormattedMessage.FromMarkup(location.Replace(' ', '\n'));
        Location.SetMessage(formattedLocation);
    }

    private FormattedMessage GetMessage(string res)
    {
        return FormattedMessage.FromMarkup(Loc.GetString(res));
    }

    private Color GetStatusColor(BankTransaction transaction)
    {
        var color = transaction.Status switch
        {
            BankTransactionStatus.Success => "#358741",
            _ => "#B22B2B"
        };

        return Color.FromHex(color);
    }

    private string GetTransactionSum(BankTransaction transaction)
    {
        var sign = transaction.Type switch
        {
            BankTransactionType.Deposit or BankTransactionType.Salary => "+",
            _ => "-"
        };

        return $"{sign}{transaction.Amount}";
    }

    private Color GetSumColor(BankTransaction transaction)
    {
        var color = transaction.Type switch
        {
            BankTransactionType.Deposit or BankTransactionType.Salary => "#358741",
            _ => "#B22B2B"
        };

        return Color.FromHex(color);
    }
}
