using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Shared.RPSX.Patron;
using Content.Shared.RPSX.Sponsors;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.RPSX.Patron.Ghost.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorGhostWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ISponsorsManager _sponsors = default!;
    [Dependency] private readonly IEntityManager _ent = default!;

    private readonly SpriteSystem _spriteSystem;

    public Action<string>? OnSelectGhost = null;

    public SponsorGhostWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _spriteSystem = _ent.System<SpriteSystem>();
    }

    public void PopulateItems()
    {
        var ghostsList = new List<string>();

        if (_sponsors.TryGetSponsorTier(out var tier))
        {
            ghostsList = tier.Ghosts;
        }

        GhostsContainer.RemoveAllChildren();

        foreach (var item in ghostsList)
        {
            if (!_prototype.TryIndex(item, out SponsorGhostCategories? proto))
                continue;

            var vBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 4,
                Margin = new Thickness(8, 8, 8, 8),
            };
            var hbox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            var texture = new TextureRect
            {
                Texture = _spriteSystem.Frame0(proto.Icon),
                MinWidth = 64,
                MinHeight = 64,
                TextureScale = new Vector2(2, 2),
                Margin = new Thickness(8, 8, 8, 8),
            };

            var label = new Label
            {
                Text = proto.Name,
            };

            var button = new Button
            {
                Text = Loc.GetString("personal-items-ghost-skins-select"),
                Margin = new Thickness(8, 8, 8, 8),
            };

            button.OnPressed += _ => OnSelectGhost?.Invoke(proto.ID);

            hbox.AddChild(texture);
            hbox.AddChild(label);
            vBox.AddChild(hbox);
            vBox.AddChild(button);


            GhostsContainer.AddChild(vBox);
        }
    }
}
